package com.prod.evergreen.helper



object ConstantValues {

    const val FILENAME_FORMAT = "yyyy-MM-dd-HH-mm-ss-SSS"
    const val Privacypolocy = "https://www.cerohero.com/privacypolicy"
    const val Termsandcondition = "https://www.cerohero.com/termsandconditions"
    const val Webpage = "https://www.cerohero.com"
    const val IMAGE_BASE_URL = "https://api.zeroheros.io"
    val PREF_IS_LOGIN = "PREF_IS_LOGIN"
    val PREF_USERNAME = "PREF_USERNAME"
    val BASE_URL = "BASE_URL"
    val PREF_FIRST_NAME = "PREF_FIRST_NAME"
    val UPDATE_PLANT_LISTDATA = "update_plant_listdata"
    val WorkOutId = "WorkOutId"
    val WorkOutStarted = "WorkOutStarted"
    val PREF_LAST_NAME = "PREF_LAST_NAME"
    val ONBOARDED = "onboarded"
    val PREF_COUNTRY_ID = "PREF_CountryID"
    val PREF_CARBON_FOOTPRINT = "carbonFootprint"
    val CalculatedDate = "calculatedDate"
    val PREF_ID = "PREF_ID"
    val USER_ID = "USER_ID"
    val AuthToken = "auth_token"
    val NEED_UPDATE = "need_update"
    val TYPE_LOGIN = "TYPE_LOGIN"
    val TYPE_ROLE = "TYPE_ROLE"
    val WROKOUTDATA = "WROKOUT_DATA"
    val FootPrint = "FootPrint"
    val WROKOUTID="WROKOUT_ID"
    val WROKOUTCO="WROKOUT_CO"
    val WOROUTSETDURATION="WOROUT_SETDURATION"
    val PREF_EMAIL = "PREF_EMAIL"
    val CERO_POINTS= "ceropoints"
    val PREF_COUNTRY = "Country"
    val PREF_GENDER = "GENDER"
    val PREF_EMAIL_VARIFIED = "PREF_EMAIL_VERIFIED"
    val PREF_BLC = "PREF_BLC"
    val PREF_MOBILE = "PREF_Mobile"
    val PREF_AMC = "PREF_AMC"
    val PREF_PASSWORD = "PREF_PASSWORD"
    val PREFCM_Tooken = "FcmTooken"
    val PROFILEIMAGE = "Profileimage"
    var ProfileImageURL="ProfileImageURL"
    var NEXTSURVEYDATE="nextsurveydate"
    val REFFERAL_LINK = "rflink"
    val PREF_fcmyoken_isupdate = "fcmyoken_isupdate"

    val KYCSTATUS_INDIVIDUAL = "KYCSTATUS_INDIVIDUAL"
    val KYCTYPE_INDIVIDUAL = "KYCTYPE_INDIVIDUAL"
    val KYCTYPE_CORPORATE = "KYCTYPE_CORPORATE"
    val KYCSTATUS_CORPORATE = "KYCSTATUS_CORPORATE"
    val APPLICATION_ID = "Applicationid"
    val WebUrl = "webUrl"


    const val DATE_OF_BIRTH = "dateofbirth"
    const val Date = "date"
    const val Units = "units"
    const val Steps = "steps"
    const val GOOGLE = "google"
    const val FACEBOOK = "facebook"
    const val TYPEEMAIL = "email"
    const val Time = "time"
    const val Isrunning = "Isrunning"
    const val REQUEST_CODE_ACTIVITY_TRANSITION = 123
    const val REQUEST_CODE_INTENT_ACTIVITY_TRANSITION = 122
    const val ACTIVITY_TRANSITION_NOTIFICATION_ID = 111
    const val ACTIVITY_TRANSITION_STORAGE = "ACTIVITY_TRANSITION_STORAGE"


    const val COUNTRY = "countryId"
    const val TotalPeson = "totalPersons"
    const val Electricity = "electricity"
    const val RenewalPercentage = "renewalPercentage"
    const val Gas = "gas"
    const val Coal = "coal"
    const val Wood = "wood"
    const val Flight = "flight"
    const val Rail = "rail"
    const val Metro = "metro"
    const val NormalBus = "normalBus"
    const val Petrol2w = "petrol2w"
    const val Petrol3w = "petrol3w"
    const val PetrolCar = "petrolCar"
    const val DieselCar = "dieselCar"
    const val CngCar = "cngCar"
    const val EleBus = "eleBus"
    const val Electric2w = "electric2w"
    const val ElectricCar = "electricCar"
    const val Vegan = "vegan"
    const val Veg = "veg"
    const val NonVeg = "nonVeg"
    const val MostMeals = "mostMeals"
    const val SomeMeals = "someMeals"
    const val Rarely = "rarely"


    const val COMAPNY_LINK="company_link"
    const val BRANCH_NAME="branch_name"
    const val COMPANYNAME="company_name"
    const val LOCATION="location"
    const val COMPANY_EMAIL="company_email"


}